﻿DROP TABLE YELP_DATA;
CREATE TABLE YELP_DATA (
    category STRING,
    rate STRING,
    name STRING,
    address STRING,
    url STRING,
    price_range STRING
)ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;

LOAD DATA INPATH 's3://lilybuckettest3210/input/final_yelp_data.csv' OVERWRITE INTO TABLE YELP_DATA;

INSERT OVERWRITE DIRECTORY 's3://lilybuckettest3210/output/hive/yelp_data' SELECT
  name,category,rate,price_range FROM YELP_DATA;